# -*- mode: ruby -*-
# vi: set ft=ruby :
VAGRANTFILE_API_VERSION = '2'.freeze

ubuntu = 'ubuntu/xenial64'
id_rsa = File.read("#{Dir.home}/.ssh/id_rsa.pub")

nodes = [
	{box: ubuntu, name: 'ansible-wp', hostname: 'web-node', memory: '1024', ip: '192.168.33.30'},
	{box: ubuntu, name: 'ansible-db', hostname: 'db-node', memory: '1024', ip: '192.168.33.40'}]
	
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  nodes.each do |nodes| # DESCRIBE NODES
    config.vm.define nodes[:name] do |node|

      node.vm.box = nodes[:box]
      node.vm.network "private_network", ip: nodes[:ip] 
      node.vm.hostname = nodes[:hostname]

      node.vm.provider :virtualbox do |vb|
        vb.name = nodes[:name]
        vb.memory = nodes[:memory]
      end

      node.vm.provision "shell", inline: <<-SHELL       
        echo '#{id_rsa}' >> .ssh/authorized_keys
      SHELL

    end
  end

end