---
- name: Download WordPress  
  copy: 
    src: "{{ path_to_artifact }}" 
    dest: /tmp/wordpress.tar.gz

- name: Remove old files
  file: 
    path: /var/www/html/
    state: absent

- name: Create directory fo wordpress
  file:
    path: /var/www/html
    state: directory

- name: Extract WordPress  
  unarchive: 
    src: /tmp/wordpress.tar.gz 
    dest: /var/www/html
    copy: no 

- name: Update WordPress config file
  template:
    src: wp-config.php.j2
    dest: /var/www/html/wp-config.php
